# -*- coding: utf-8 -*-
"""CODSOFT-TASK3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGVVLpDEU87MCkhv7AHGe49EaVUuUQel
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/IRIS.csv')

df

#Finding the data types of variables in the DataFrame
df.dtypes

# Commented out IPython magic to ensure Python compatibility.
#Importing libraries essential for data visualization
#MATPLOTLIB
import matplotlib.pyplot as plt
# %matplotlib inline

#SEABORN
import seaborn as sns

#Plots for continuous variables' analysis
#ENUMERATIVE PLOTS
#UNIVARIATE SCATTER PLOT
plt.scatter(df.index,df['sepal_width'])
plt.show()

sns.scatterplot(x=df.index,y=df['sepal_width'],hue=df['species'])

#LINE PLOT WITH MARKERS
#Setting title, figure size, labels and font size in matplotlib

plt.figure(figsize=(6,6))
plt.title('Line plot of petal length')
plt.xlabel('index',fontsize=20)
plt.ylabel('petal length',fontsize=20)
plt.plot(df.index,df['petal_length'],markevery=1,marker='d')

for name, group in df.groupby('species'):
    plt.plot(group.index, group['petal_length'], label=name,markevery=1,marker='d')
plt.legend()
plt.show()

#Setting title, figure size,labels and font size in seaborn
sns.set(rc={'figure.figsize':(7,7)})
sns.set(font_scale=1.5)
fig=sns.lineplot(x=df.index,y=df['petal_length'],markevery=1,marker='d',data=df,hue=df['species'])
fig.set(xlabel='index')

#STRIP PLOT
sns.stripplot(y=df['sepal_width'])

# Strip-plot(category wise)
sns.stripplot(x=df['species'],y=df['sepal_width'])

#SWARM PLOT
#Setting figure size
sns.set(rc={'figure.figsize':(5,5)})

#Swarm-plot
sns.swarmplot(x=df['sepal_width'])

#Swarm-plot category wise
sns.swarmplot(x=df['species'],y=df['sepal_width'])

#SUMMARY PLOTS
#HISTOGRAM
plt.hist(df['petal_width'])
sns.distplot(df['petal_width'],kde=False,color='black',bins=10)

#DENSITY PLOT
plt.figure(figsize=(5,5))
df['petal_length'].plot(kind='density')

sns.set(rc={'figure.figsize':(5,5)})
sns.kdeplot(df['petal_length'],shade=True)

#RUG PLOT
fig, ax = plt.subplots()
sns.rugplot(df['sepal_length'])
ax.set_xlim(3,9)
plt.show()

from scipy import stats
import numpy as np
kdf=df['sepal_length'].to_numpy()
rdf=np.hstack(kdf)
density = stats.kde.gaussian_kde(rdf)
x = np.arange(3,9,0.1)
plt.plot(x, density(x))
plt.plot(rdf,[0.01]*len(rdf), '|')

sns.distplot(df['sepal_length'],rug=True,hist=False)

#BOX PLOT
plt.boxplot(df['sepal_width'])

#Removing the column with categorical variables
dfM=df.drop('species',axis=1)
plt.figure(figsize=(9,9))

#Set Title
plt.title('Box plots of the 4 variables')
plt.boxplot(dfM.values,labels=['SepalLength','SepalWidth','PetalLength','PetalWidth'])

sns.boxplot(df['sepal_width'])

sns.set(rc={'figure.figsize':(9,9)})
sns.boxplot(x="variable", y="value", data=pd.melt(dfM))

#distplot()
sns.set(rc={'figure.figsize':(6,6)})
sns.distplot(df['petal_length'],color='black',rug=True)

#VIOLIN PLOT
plt.figure(figsize=(7,7))
plt.violinplot(dfM.values,showmedians=True)

sns.set(rc={'figure.figsize':(5,5)})
sns.violinplot(df['sepal_width'],orient='vertical')

sns.set(rc={'figure.figsize':(9,9)})
sns.violinplot(x=df['species'], y=df['petal_width'],data=df)

#Plots for categorical variables' analysis
#BAR PLOT
df['species'].value_counts().plot.bar()

sns.countplot(df['species'])

#PIE CHART
plt.pie(df['species'].value_counts(),labels=['SETOSA','VERSICOLOR','VIRGINICA'],shadow=True)
df1=df.sample(frac=0.35)

plt.figure(figsize=(5,5))
plt.pie(df1['species'].value_counts(),startangle=90,autopct='%.3f',labels=['SETOSA','VERSICOLOR','VIRGINICA'],shadow=True)